name: Maestro Cloud Tests

on:
  push:
    branches: [ "master" ]

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download APK de forma rápida
        run: |
          curl -L -o app-teste.apk "https://github.com/matheuszanellasma/automacao-mobile-maestro/releases/download/v1.0/qazandofood.apk"

      - name: Run tests on Maestro Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v2.0.2
        with:
          api-key: ${{ secrets.MAESTRO_API_KEY }}
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }}
          app-file: app-teste.apk        
          workspace: flows
          include-tags: smoke